[build]
  publish = "."

# Force HTTPS and remove www
[[redirects]]
  from = "http://neverleavetheplayground.com/*"
  to = "https://neverleavetheplayground.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.neverleavetheplayground.com/*"
  to = "https://neverleavetheplayground.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.neverleavetheplayground.com/*"
  to = "https://neverleavetheplayground.com/:splat"
  status = 301
  force = true

# Manual known mapping
[[redirects]]
  from = "/our-videos-old.html"
  to = "/our-videos.html"
  status = 301

# Optional SPA fallback (keep last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
